export const PROFILE_STRINGS = {
  title: 'My profile',
  signedInAs: 'Signed in as the account owner',
  logout: 'Log out',
  editProfile: 'Edit profile',
  edit: 'Edit',
  changePassword: 'Change password',
  password: 'Password',
  contact: 'Contact details',
  email: 'Email',
  phone: 'Phone number',
  designation: 'Designation',
  organization: 'Organization',
  role: 'Role',
  status: 'Status',
  memberSince: 'Member since',
  admin: 'Admin',
  user: 'User',
  active: 'Active',
  editTitle: 'Edit profile',
  editSubtitle: 'Update how you appear to your team.',
  fields: {
    name: 'Full name',
    designation: 'Designation',
    phone: 'Phone number',
    phonePlaceholder: 'e.g. +91 98765 43210',
    currentPassword: 'Current password',
    currentPasswordPlaceholder: 'Enter your current password',
    newPassword: 'New password',
    newPasswordPlaceholder: 'Create a new password',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: 'Re-enter new password',
  },
  passwordTitle: 'Change password',
  passwordSubtitle: 'Choose a new password for your account.',
  passwordSubmit: 'Update password',
  passwordRulesUnmet: 'The new password doesn’t meet the rules below',
  logoutTitle: 'Log out?',
  logoutMessage: 'You’ll need to sign in again to use N1.',
} as const;
