import { DAY_MS, HOUR_MS, isoAgo } from '../../../services/mock/mockServer';
import type { Customer } from '../types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUS-1',
    type: 'business',
    name: 'Acme Metalworks',
    contactPerson: 'Rajesh Kumar',
    mobile: '+91 98765 43210',
    email: 'accounts@acmemetalworks.com',
    gstNumber: '33AAAAA0000A1Z5',
    address: '12 Industrial Estate Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    notes: 'Long-standing bracket supplier account.',
    currentProjects: 12,
    previousProjects: 27,
    totalRevenue: 1842000,
    outstandingBalance: 212000,
    customerSince: '2025-01-12',
    activity: [
      {
        id: 'a1',
        label: 'New order placed — Job A',
        at: isoAgo(2 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Invoice #1042 sent',
        at: isoAgo(DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Account added',
        at: '2025-01-12T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-2',
    type: 'business',
    name: 'Bright Steel Co.',
    contactPerson: 'Meera Nair',
    mobile: '+91 98840 22110',
    email: 'purchase@brightsteel.in',
    gstNumber: '33BBBBB1111B1Z6',
    address: '45 SIDCO Industrial Estate',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    notes: 'Prefers weekly dispatch on Fridays.',
    currentProjects: 8,
    previousProjects: 19,
    totalRevenue: 1215000,
    outstandingBalance: 148500,
    customerSince: '2025-03-04',
    activity: [
      {
        id: 'a1',
        label: 'QC report shared — Job B',
        at: isoAgo(5 * HOUR_MS),
        tone: 'info',
      },
      {
        id: 'a2',
        label: 'Account added',
        at: '2025-03-04T11:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-3',
    type: 'business',
    name: 'Nova Fabrication',
    contactPerson: 'Suresh Pillai',
    mobile: '+91 99620 45120',
    email: 'orders@novafab.co.in',
    gstNumber: '29CCCCC2222C1Z7',
    address: '',
    city: 'Bengaluru',
    state: 'Karnataka',
    notes: '',
    currentProjects: 5,
    previousProjects: 14,
    totalRevenue: 684000,
    outstandingBalance: 35600,
    customerSince: '2025-05-19',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-05-19T09:30:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-4',
    type: 'business',
    name: 'Silverline Industries',
    contactPerson: 'Anita Desai',
    mobile: '+91 90030 77881',
    email: 'accounts@silverline.in',
    gstNumber: '',
    address: '',
    city: '',
    state: 'Tamil Nadu',
    notes: '',
    currentProjects: 3,
    previousProjects: 9,
    totalRevenue: 402000,
    outstandingBalance: 21900,
    customerSince: '2025-08-02',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-08-02T15:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-5',
    type: 'individual',
    name: 'Meridian Components',
    contactPerson: 'Vikram Rao',
    mobile: '+91 94440 11223',
    email: '',
    gstNumber: '',
    address: '',
    city: 'Chennai',
    state: 'Tamil Nadu',
    notes: '',
    currentProjects: 2,
    previousProjects: 6,
    totalRevenue: 296000,
    outstandingBalance: 58400,
    customerSince: '2025-11-21',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-11-21T12:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-6',
    type: 'business',
    name: 'Precision Gears Pvt Ltd',
    contactPerson: 'Karthik Subramanian',
    mobile: '+91 98410 55667',
    email: 'orders@precisiongears.in',
    gstNumber: '33DDDDD3333D1Z8',
    address: '8 Ambattur Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    notes: 'Gearbox housings; needs CMM reports.',
    currentProjects: 4,
    previousProjects: 11,
    totalRevenue: 538000,
    outstandingBalance: 64200,
    customerSince: '2025-02-18',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-02-18T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-7',
    type: 'business',
    name: 'Deccan Auto Parts',
    contactPerson: 'Farhan Siddiqui',
    mobile: '+91 90000 31245',
    email: 'purchase@deccanauto.com',
    gstNumber: '36EEEEE4444E1Z9',
    address: 'Plot 21, IDA Uppal',
    city: 'Hyderabad',
    state: 'Telangana',
    notes: '',
    currentProjects: 6,
    previousProjects: 15,
    totalRevenue: 876000,
    outstandingBalance: 121000,
    customerSince: '2025-04-09',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-04-09T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-8',
    type: 'business',
    name: 'Kaveri Hydraulics',
    contactPerson: 'Lakshmi Narayan',
    mobile: '+91 97890 44120',
    email: 'accounts@kaverihydraulics.in',
    gstNumber: '29FFFFF5555F1Z1',
    address: '',
    city: 'Mysuru',
    state: 'Karnataka',
    notes: 'Cylinder rods, chrome plated.',
    currentProjects: 3,
    previousProjects: 8,
    totalRevenue: 412000,
    outstandingBalance: 0,
    customerSince: '2025-06-27',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-06-27T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-9',
    type: 'business',
    name: 'Western Pumps & Valves',
    contactPerson: 'Nikhil Joshi',
    mobile: '+91 98220 78901',
    email: 'po@westernpumps.co.in',
    gstNumber: '27GGGGG6666G1Z2',
    address: 'MIDC Bhosari',
    city: 'Pune',
    state: 'Maharashtra',
    notes: '',
    currentProjects: 5,
    previousProjects: 12,
    totalRevenue: 693000,
    outstandingBalance: 87500,
    customerSince: '2025-07-14',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-07-14T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-10',
    type: 'business',
    name: 'Sakthi Engineering Works',
    contactPerson: 'Senthil Murugan',
    mobile: '+91 94433 66778',
    email: 'sakthieng@gmail.com',
    gstNumber: '33HHHHH7777H1Z3',
    address: '',
    city: 'Tiruppur',
    state: 'Tamil Nadu',
    notes: 'Pays on 45-day terms.',
    currentProjects: 2,
    previousProjects: 5,
    totalRevenue: 224000,
    outstandingBalance: 48000,
    customerSince: '2025-09-03',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-09-03T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-11',
    type: 'business',
    name: 'Orion Tooling Solutions',
    contactPerson: 'Priya Menon',
    mobile: '+91 99400 12890',
    email: 'hello@oriontooling.in',
    gstNumber: '32IIIII8888I1Z4',
    address: 'Kakkanad Industrial Area',
    city: 'Kochi',
    state: 'Kerala',
    notes: '',
    currentProjects: 1,
    previousProjects: 3,
    totalRevenue: 138000,
    outstandingBalance: 22500,
    customerSince: '2025-12-08',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-12-08T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-12',
    type: 'individual',
    name: 'Arjun Prakash',
    contactPerson: 'Arjun Prakash',
    mobile: '+91 93800 45671',
    email: '',
    gstNumber: '',
    address: '',
    city: 'Madurai',
    state: 'Tamil Nadu',
    notes: 'Prototype parts for a startup.',
    currentProjects: 1,
    previousProjects: 1,
    totalRevenue: 46000,
    outstandingBalance: 46000,
    customerSince: '2026-02-15',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2026-02-15T10:00:00',
        tone: 'neutral',
      },
    ],
  },
];
