import { DAY_MS, HOUR_MS, isoAgo } from '../../../services/mock/mockServer';
import type { Customer } from '../types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUS-1',
    type: 'business',
    name: 'Acme Metalworks',
    contactPerson: 'Rajesh Kumar',
    mobile: '+91 98765 43210',
    email: 'accounts@acmemetalworks.com',
    gstNumber: '33AAAAA0000A1Z5',
    address: '12 Industrial Estate Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    notes: 'Long-standing bracket supplier account.',
    currentProjects: 12,
    previousProjects: 27,
    totalRevenue: 1842000,
    outstandingBalance: 212000,
    customerSince: '2025-01-12',
    activity: [
      {
        id: 'a1',
        label: 'New order placed — Job A',
        at: isoAgo(2 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Invoice #1042 sent',
        at: isoAgo(DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Account added',
        at: '2025-01-12T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-2',
    type: 'business',
    name: 'Bright Steel Co.',
    contactPerson: 'Meera Nair',
    mobile: '+91 98840 22110',
    email: 'purchase@brightsteel.in',
    gstNumber: '33BBBBB1111B1Z6',
    address: '45 SIDCO Industrial Estate',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    notes: 'Prefers weekly dispatch on Fridays.',
    currentProjects: 8,
    previousProjects: 19,
    totalRevenue: 1215000,
    outstandingBalance: 148500,
    customerSince: '2025-03-04',
    activity: [
      {
        id: 'a1',
        label: 'QC report shared — Job B',
        at: isoAgo(5 * HOUR_MS),
        tone: 'info',
      },
      {
        id: 'a2',
        label: 'Account added',
        at: '2025-03-04T11:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-3',
    type: 'business',
    name: 'Nova Fabrication',
    contactPerson: 'Suresh Pillai',
    mobile: '+91 99620 45120',
    email: 'orders@novafab.co.in',
    gstNumber: '29CCCCC2222C1Z7',
    address: '',
    city: 'Bengaluru',
    state: 'Karnataka',
    notes: '',
    currentProjects: 5,
    previousProjects: 14,
    totalRevenue: 684000,
    outstandingBalance: 35600,
    customerSince: '2025-05-19',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-05-19T09:30:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-4',
    type: 'business',
    name: 'Silverline Industries',
    contactPerson: 'Anita Desai',
    mobile: '+91 90030 77881',
    email: 'accounts@silverline.in',
    gstNumber: '',
    address: '',
    city: '',
    state: 'Tamil Nadu',
    notes: '',
    currentProjects: 3,
    previousProjects: 9,
    totalRevenue: 402000,
    outstandingBalance: 21900,
    customerSince: '2025-08-02',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-08-02T15:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'CUS-5',
    type: 'individual',
    name: 'Meridian Components',
    contactPerson: 'Vikram Rao',
    mobile: '+91 94440 11223',
    email: '',
    gstNumber: '',
    address: '',
    city: 'Chennai',
    state: 'Tamil Nadu',
    notes: '',
    currentProjects: 2,
    previousProjects: 6,
    totalRevenue: 296000,
    outstandingBalance: 58400,
    customerSince: '2025-11-21',
    activity: [
      {
        id: 'a1',
        label: 'Account added',
        at: '2025-11-21T12:00:00',
        tone: 'neutral',
      },
    ],
  },
];
