import { createN1Styles } from '../../../N1Modules';
import { SIDEBAR_COLLAPSED_WIDTH, SIDEBAR_WIDTH } from '../../constants';

export const makeLayoutStyles = createN1Styles(t => ({
  root: { flex: 1, flexDirection: 'row', backgroundColor: t.colors.background },
  compactRoot: { flex: 1, backgroundColor: t.colors.background },
  main: { flex: 1 },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.spacing.md,
    paddingHorizontal: t.spacing.xl,
    paddingVertical: t.spacing.md,
    backgroundColor: t.colors.surface,
    borderBottomWidth: t.borderWidth.hairline,
    borderBottomColor: t.colors.border,
  },
  topBarTitle: { flex: 1 },
  userButton: { flexDirection: 'row', alignItems: 'center', gap: t.spacing.sm },
  userText: { gap: t.spacing.xxs },
  compactBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.spacing.md,
    paddingHorizontal: t.spacing.lg,
    paddingVertical: t.spacing.md,
  },
  compactBarSafe: { backgroundColor: t.colors.surfaceInverse },
  compactTitle: { flex: 1 },
  drawerBackdrop: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: t.colors.overlay,
  },
  drawerPanel: { width: SIDEBAR_WIDTH, maxWidth: '85%' },
  drawerDismiss: { flex: 1 },
  pressed: { opacity: t.opacity.pressed },
}));

export const makeSidebarStyles = createN1Styles(t => ({
  sidebar: {
    width: SIDEBAR_WIDTH,
    backgroundColor: t.colors.surfaceInverse,
    paddingHorizontal: t.spacing.lg,
    paddingVertical: t.spacing.xl,
    gap: t.spacing.lg,
  },
  collapsed: { width: SIDEBAR_COLLAPSED_WIDTH, alignItems: 'center' },
  fill: { flex: 1 },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: t.spacing.sm,
  },
  headerButton: {
    width: t.controlHeight.sm,
    height: t.controlHeight.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: t.radius.sm,
    borderWidth: t.borderWidth.hairline,
    borderColor: t.colors.surfaceInverseActive,
  },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.spacing.sm,
    height: t.controlHeight.md,
    paddingHorizontal: t.spacing.md,
    borderRadius: t.radius.pill,
    borderWidth: t.borderWidth.hairline,
    borderColor: t.colors.surfaceInverseActive,
    backgroundColor: t.colors.surfaceInverseActive,
  },
  searchInput: {
    flex: 1,
    alignSelf: 'stretch',
    padding: 0,
    color: t.colors.textInverse,
    fontFamily: t.fontFamily.regular,
    fontSize: t.typography.small.fontSize,
    outlineWidth: 0,
  },
  sectionLabel: {
    paddingHorizontal: t.spacing.md,
    color: t.colors.textTertiary,
  },
  menu: { gap: t.spacing.xs },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.spacing.md,
    height: t.controlHeight.md,
    paddingHorizontal: t.spacing.md,
    borderRadius: t.radius.pill,
  },
  itemCollapsed: {
    justifyContent: 'center',
    paddingHorizontal: 0,
    width: t.controlHeight.md,
  },
  itemActive: { backgroundColor: t.colors.surfaceInverseActive },
  itemPressed: { opacity: t.opacity.pressed },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: t.spacing.sm,
    padding: t.spacing.md,
    borderRadius: t.radius.md,
    backgroundColor: t.colors.surfaceInverseActive,
  },
  footerText: { flex: 1, gap: t.spacing.xxs },
  inverseText: { color: t.colors.textInverse },
  mutedText: { color: t.colors.textTertiary },
}));
