import {
  DAY_MS,
  HOUR_MS,
  MINUTE_MS,
  isoAgo,
} from '../../../services/mock/mockServer';
import type { AdminUser } from '../types';

export const MOCK_USERS: AdminUser[] = [
  {
    id: 'USR-1',
    name: 'Koushik Dasarathan',
    email: 'kousigaratchagan.pd@foodhub.com',
    designation: 'Founder & Administrator',
    phone: '+91 98765 00000',
    department: 'Management',
    address: '12, 3rd Cross Street, Guindy Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600032',
    country: 'India',
    role: 'admin',
    status: 'active',
    joinedAt: '2026-09-12',
    permissions: { viewOrders: true, manageUsers: true, exportReports: true },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Chrome',
        at: isoAgo(MINUTE_MS / 2),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Created user Priya Sharma',
        at: isoAgo(2 * DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Created organization',
        at: '2026-09-12T09:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@abcengineering.com',
    designation: 'Production Supervisor',
    phone: '+91 98765 43210',
    department: 'Manufacturing Operations',
    address: '45, Anna Nagar West',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600040',
    country: 'India',
    role: 'supervisor',
    status: 'active',
    joinedAt: '2026-09-18',
    permissions: { viewOrders: true, manageUsers: false, exportReports: true },
    attachments: [
      { id: 'f1', name: 'ID proof.pdf', sizeBytes: 1.2 * 1024 * 1024 },
      { id: 'f2', name: 'Offer letter.pdf', sizeBytes: 340 * 1024 },
    ],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Chrome',
        at: isoAgo(2 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Updated designation',
        at: isoAgo(DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Account created',
        at: '2026-09-18T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-3',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@abcengineering.com',
    designation: 'CNC Operator',
    phone: '+91 98765 11122',
    department: 'Machining',
    address: '8, Ambattur Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600058',
    country: 'India',
    role: 'operator',
    status: 'invited',
    joinedAt: '2026-09-20',
    permissions: { viewOrders: true, manageUsers: false, exportReports: false },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Invitation sent',
        at: '2026-09-20T11:30:00',
        tone: 'info',
      },
    ],
  },
  {
    id: 'USR-4',
    name: 'Divya Rao',
    email: 'divya.rao@abcengineering.com',
    designation: 'QC Inspector',
    phone: '+91 98765 33344',
    department: 'Quality',
    address: '21, Gandhipuram 2nd Street',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    pinCode: '641012',
    country: 'India',
    role: 'qc',
    status: 'active',
    joinedAt: '2026-09-22',
    permissions: { viewOrders: true, manageUsers: false, exportReports: true },
    attachments: [
      { id: 'f1', name: 'Certification.pdf', sizeBytes: 820 * 1024 },
    ],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Safari',
        at: isoAgo(5 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Account created',
        at: '2026-09-22T09:15:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-5',
    name: 'Karthik Iyer',
    email: 'karthik.iyer@abcengineering.com',
    designation: 'Machinist',
    phone: '+91 98765 55566',
    department: 'Machining',
    address: '17, Velachery Main Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600042',
    country: 'India',
    role: 'operator',
    status: 'suspended',
    joinedAt: '2026-09-24',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account suspended',
        at: isoAgo(3 * DAY_MS),
        tone: 'danger',
      },
      {
        id: 'a2',
        label: 'Account created',
        at: '2026-09-24T14:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-6',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@abcengineering.com',
    designation: 'Deburring Operator',
    phone: '+91 98765 60222',
    department: 'Finishing',
    address: '5, Peenya Industrial Area',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560058',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-09-25',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-25T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-7',
    name: 'Suresh Babu',
    email: 'suresh.babu@abcengineering.com',
    designation: 'QC Inspector',
    phone: '+91 98765 60259',
    department: 'Quality',
    address: '12, 3rd Cross Street, Guindy Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600032',
    country: 'India',
    role: 'qc',
    status: 'active',
    joinedAt: '2026-09-25',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-25T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-8',
    name: 'Arun Prakash',
    email: 'arun.prakash@abcengineering.com',
    designation: 'CNC Lathe Operator',
    phone: '+91 98765 60296',
    department: 'Machining',
    address: '45, Anna Nagar West',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600040',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-09-26',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-26T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-9',
    name: 'Divya Ramesh',
    email: 'divya.ramesh@abcengineering.com',
    designation: 'Welder',
    phone: '+91 98765 60333',
    department: 'Fabrication',
    address: '8, Ambattur Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600058',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-09-26',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-26T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-10',
    name: 'Anand Krishnan',
    email: 'anand.krishnan@abcengineering.com',
    designation: 'Shift Supervisor',
    phone: '+91 98765 60370',
    department: 'Manufacturing Operations',
    address: '21, Gandhipuram 2nd Street',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    pinCode: '641012',
    country: 'India',
    role: 'supervisor',
    status: 'active',
    joinedAt: '2026-09-27',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: true,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-27T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-11',
    name: 'Lakshmi Venkat',
    email: 'lakshmi.venkat@abcengineering.com',
    designation: 'QC Engineer',
    phone: '+91 98765 60407',
    department: 'Quality',
    address: '17, Velachery Main Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600042',
    country: 'India',
    role: 'qc',
    status: 'invited',
    joinedAt: '2026-09-27',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-27T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-12',
    name: 'Mohammed Irfan',
    email: 'mohammed.irfan@abcengineering.com',
    designation: 'VMC Operator',
    phone: '+91 98765 60444',
    department: 'Machining',
    address: '5, Peenya Industrial Area',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560058',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-09-28',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-28T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-13',
    name: 'Sneha Pillai',
    email: 'sneha.pillai@abcengineering.com',
    designation: 'Stores Supervisor',
    phone: '+91 98765 60481',
    department: 'Stores',
    address: '12, 3rd Cross Street, Guindy Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600032',
    country: 'India',
    role: 'supervisor',
    status: 'active',
    joinedAt: '2026-09-28',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: true,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-28T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-14',
    name: 'Vignesh Raj',
    email: 'vignesh.raj@abcengineering.com',
    designation: 'Grinding Operator',
    phone: '+91 98765 60518',
    department: 'Finishing',
    address: '45, Anna Nagar West',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600040',
    country: 'India',
    role: 'operator',
    status: 'inactive',
    joinedAt: '2026-09-29',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-29T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-15',
    name: 'Kavya Nair',
    email: 'kavya.nair@abcengineering.com',
    designation: 'QC Inspector',
    phone: '+91 98765 60555',
    department: 'Quality',
    address: '8, Ambattur Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600058',
    country: 'India',
    role: 'qc',
    status: 'active',
    joinedAt: '2026-09-29',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-29T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-16',
    name: 'Ganesh Moorthy',
    email: 'ganesh.moorthy@abcengineering.com',
    designation: 'Fitter',
    phone: '+91 98765 60592',
    department: 'Assembly',
    address: '21, Gandhipuram 2nd Street',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    pinCode: '641012',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-09-30',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-30T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-17',
    name: 'Pooja Reddy',
    email: 'pooja.reddy@abcengineering.com',
    designation: 'Planning Supervisor',
    phone: '+91 98765 60629',
    department: 'Production Planning',
    address: '17, Velachery Main Road',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600042',
    country: 'India',
    role: 'supervisor',
    status: 'invited',
    joinedAt: '2026-09-30',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: true,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-09-30T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-18',
    name: 'Harish Chandran',
    email: 'harish.chandran@abcengineering.com',
    designation: 'Milling Operator',
    phone: '+91 98765 60666',
    department: 'Machining',
    address: '5, Peenya Industrial Area',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560058',
    country: 'India',
    role: 'operator',
    status: 'suspended',
    joinedAt: '2026-10-01',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-10-01T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-19',
    name: 'Nithya Sekar',
    email: 'nithya.sekar@abcengineering.com',
    designation: 'Metrology Technician',
    phone: '+91 98765 60703',
    department: 'Quality',
    address: '12, 3rd Cross Street, Guindy Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600032',
    country: 'India',
    role: 'qc',
    status: 'active',
    joinedAt: '2026-10-01',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-10-01T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-20',
    name: 'Bala Subramani',
    email: 'bala.subramani@abcengineering.com',
    designation: 'Press Operator',
    phone: '+91 98765 60740',
    department: 'Fabrication',
    address: '45, Anna Nagar West',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600040',
    country: 'India',
    role: 'operator',
    status: 'active',
    joinedAt: '2026-10-02',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-10-02T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-21',
    name: 'Deepak Menon',
    email: 'deepak.menon@abcengineering.com',
    designation: 'Maintenance Supervisor',
    phone: '+91 98765 60777',
    department: 'Maintenance',
    address: '8, Ambattur Industrial Estate',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600058',
    country: 'India',
    role: 'supervisor',
    status: 'active',
    joinedAt: '2026-10-02',
    permissions: {
      viewOrders: true,
      manageUsers: false,
      exportReports: true,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-10-02T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-22',
    name: 'Revathi Ganesan',
    email: 'revathi.ganesan@abcengineering.com',
    designation: 'Packing Operator',
    phone: '+91 98765 60814',
    department: 'Dispatch',
    address: '21, Gandhipuram 2nd Street',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    pinCode: '641012',
    country: 'India',
    role: 'operator',
    status: 'invited',
    joinedAt: '2026-10-03',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account created',
        at: '2026-10-03T10:00:00',
        tone: 'neutral',
      },
    ],
  },
];
