import {
  DAY_MS,
  HOUR_MS,
  MINUTE_MS,
  isoAgo,
} from '../../../services/mock/mockServer';
import type { AdminUser } from '../types';

export const MOCK_USERS: AdminUser[] = [
  {
    id: 'USR-1',
    name: 'Koushik Dasarathan',
    email: 'kousigaratchagan.pd@foodhub.com',
    designation: 'Founder & Administrator',
    phone: '+91 98765 00000',
    department: 'Management',
    role: 'admin',
    status: 'active',
    joinedAt: '2026-09-12',
    permissions: { viewOrders: true, manageUsers: true, exportReports: true },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Chrome',
        at: isoAgo(MINUTE_MS / 2),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Created user Priya Sharma',
        at: isoAgo(2 * DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Created organization',
        at: '2026-09-12T09:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@abcengineering.com',
    designation: 'Production Supervisor',
    phone: '+91 98765 43210',
    department: 'Manufacturing Operations',
    role: 'supervisor',
    status: 'active',
    joinedAt: '2026-09-18',
    permissions: { viewOrders: true, manageUsers: false, exportReports: true },
    attachments: [
      { id: 'f1', name: 'ID proof.pdf', sizeBytes: 1.2 * 1024 * 1024 },
      { id: 'f2', name: 'Offer letter.pdf', sizeBytes: 340 * 1024 },
    ],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Chrome',
        at: isoAgo(2 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Updated designation',
        at: isoAgo(DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Account created',
        at: '2026-09-18T10:00:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-3',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@abcengineering.com',
    designation: 'CNC Operator',
    phone: '+91 98765 11122',
    department: 'Machining',
    role: 'operator',
    status: 'invited',
    joinedAt: '2026-09-20',
    permissions: { viewOrders: true, manageUsers: false, exportReports: false },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Invitation sent',
        at: '2026-09-20T11:30:00',
        tone: 'info',
      },
    ],
  },
  {
    id: 'USR-4',
    name: 'Divya Rao',
    email: 'divya.rao@abcengineering.com',
    designation: 'QC Inspector',
    phone: '+91 98765 33344',
    department: 'Quality',
    role: 'qc',
    status: 'active',
    joinedAt: '2026-09-22',
    permissions: { viewOrders: true, manageUsers: false, exportReports: true },
    attachments: [
      { id: 'f1', name: 'Certification.pdf', sizeBytes: 820 * 1024 },
    ],
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Safari',
        at: isoAgo(5 * HOUR_MS),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Account created',
        at: '2026-09-22T09:15:00',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'USR-5',
    name: 'Karthik Iyer',
    email: 'karthik.iyer@abcengineering.com',
    designation: 'Machinist',
    phone: '+91 98765 55566',
    department: 'Machining',
    role: 'operator',
    status: 'suspended',
    joinedAt: '2026-09-24',
    permissions: {
      viewOrders: false,
      manageUsers: false,
      exportReports: false,
    },
    attachments: [],
    activity: [
      {
        id: 'a1',
        label: 'Account suspended',
        at: isoAgo(3 * DAY_MS),
        tone: 'danger',
      },
      {
        id: 'a2',
        label: 'Account created',
        at: '2026-09-24T14:00:00',
        tone: 'neutral',
      },
    ],
  },
];
