import { DAY_MS, MINUTE_MS, isoAgo } from '../../../services/mock/mockServer';
import type { Session } from '../types';

export const MOCK_SESSION: Session = {
  organization: {
    id: 'ORG-1',
    code: 'ABC001',
    createdAt: '2026-09-12',
    shortName: 'ABC Engineering',
    name: 'ABC Engineering Pvt Ltd',
    logo: null,
    phone: '+91 44 4000 1000',
    email: 'admin@abcengineering.com',
    website: 'www.abcengineering.com',
    businessType: 'private-limited',
    industry: 'metal-manufacturing',
    registrationDetails: 'CIN U28910TN2018PTC123456',
    address: 'Plot 14, SIDCO Industrial Estate, Ambattur',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600098',
    country: 'India',
    gstRegistered: true,
    gstNumber: '33ABCDE1234F1Z5',
    gstState: 'Tamil Nadu',
    taxRates: [
      { id: 'rate-5', rate: 5, active: true },
      { id: 'rate-12', rate: 12, active: true },
      { id: 'rate-18', rate: 18, active: true },
      { id: 'rate-28', rate: 28, active: false },
    ],
    defaultTaxRate: 18,
    invoicePrefix: 'INV-2026-',
    invoiceStartNumber: 101,
    invoiceFooter: 'Thank you for your business.',
    invoiceLogo: null,
    termsAndConditions:
      'Payment is due within 30 days. Goods once dispatched will not be taken back.',
    signature: null,
  },
  profile: {
    id: 'USR-1',
    name: 'Koushik Dasarathan',
    email: 'kousigaratchagan.pd@foodhub.com',
    designation: 'Founder & Administrator',
    phone: '+91 98765 00000',
    photo: null,
    hasPassword: true,
    address: '12, 3rd Cross Street, Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600040',
    country: 'India',
    role: 'admin',
    status: 'active',
    memberSince: '2026-09-12',
    activity: [
      {
        id: 'a1',
        label: 'Logged in from Chrome',
        at: isoAgo(MINUTE_MS / 2),
        tone: 'success',
      },
      {
        id: 'a2',
        label: 'Created user Priya Sharma',
        at: isoAgo(2 * DAY_MS),
        tone: 'info',
      },
      {
        id: 'a3',
        label: 'Created organization',
        at: '2026-09-12T09:00:00',
        tone: 'neutral',
      },
    ],
  },
};
