import type { Machine } from '../types';

const m = (machine: Omit<Machine, 'notes'> & { notes?: string }): Machine => ({
  notes: '',
  ...machine,
});

export const MOCK_MACHINES: Machine[] = [
  m({
    id: 'MCH-1',
    code: 'CNC-01',
    name: 'Turning Center 1',
    model: 'Haas ST-20',
    type: 'cnc_lathe',
    location: 'Bay 1',
    status: 'running',
    currentWork: {
      workOrderId: '1036',
      title: 'Coupling — Job G',
      operator: 'Divya Ramesh',
    },
  }),
  m({
    id: 'MCH-2',
    code: 'CNC-02',
    name: 'Turning Center 2',
    model: 'Haas ST-20',
    type: 'cnc_lathe',
    location: 'Bay 1',
    status: 'running',
    currentWork: {
      workOrderId: '1039',
      title: 'Flange — Job C',
      operator: 'Karthik Iyer',
    },
  }),
  m({
    id: 'MCH-3',
    code: 'CNC-03',
    name: 'Milling Center 1',
    model: 'DMG Mori NVX',
    type: 'cnc_mill',
    location: 'Bay 2',
    status: 'maintenance',
    currentWork: null,
    notes: 'Spindle bearing replacement scheduled this week.',
  }),
  m({
    id: 'MCH-4',
    code: 'CNC-04',
    name: 'Milling Center 2',
    model: 'DMG Mori NVX',
    type: 'cnc_mill',
    location: 'Bay 2',
    status: 'running',
    currentWork: {
      workOrderId: '1042',
      title: 'Bracket — Job A',
      operator: 'Arun Prakash',
    },
  }),
  m({
    id: 'MCH-5',
    code: 'LATHE-01',
    name: 'Manual Lathe 1',
    model: 'Kirloskar Turnmaster',
    type: 'lathe',
    location: 'Bay 1',
    status: 'idle',
    currentWork: null,
  }),
  m({
    id: 'MCH-6',
    code: 'WELD-01',
    name: 'Weld Station 1',
    model: 'Miller Syncrowave',
    type: 'welding',
    location: 'Bay 3',
    status: 'running',
    currentWork: {
      workOrderId: '1037',
      title: 'Bracket — Job F',
      operator: 'Arun Prakash',
    },
  }),
  m({
    id: 'MCH-7',
    code: 'WELD-02',
    name: 'Weld Station 2',
    model: 'Miller Syncrowave',
    type: 'welding',
    location: 'Bay 3',
    status: 'idle',
    currentWork: null,
  }),
  m({
    id: 'MCH-8',
    code: 'QC-01',
    name: 'QC Bay 1',
    model: 'Mitutoyo CMM',
    type: 'inspection',
    location: 'QC Zone',
    status: 'running',
    currentWork: {
      workOrderId: '1040',
      title: 'Bracket — Job B',
      operator: 'Suresh Babu',
    },
  }),
  m({
    id: 'MCH-9',
    code: 'QC-02',
    name: 'QC Bay 2',
    model: 'Mitutoyo CMM',
    type: 'inspection',
    location: 'QC Zone',
    status: 'idle',
    currentWork: null,
  }),
  m({
    id: 'MCH-10',
    code: 'PACK-01',
    name: 'Pack Station 1',
    model: 'Manual line',
    type: 'packing',
    location: 'Bay 4',
    status: 'maintenance',
    currentWork: null,
  }),
];
